### ISSUE TITLE
Crear una lista de fragments para que se muestren cosas distintas para cada tab

### ISSUE THREAD

**Issue by crzyivo** [UNIZAR-30226-2017-04/barestv-android#3]
Actualmente solo se puede mostrar un fragment en todas las tabs _provisionalmente el de busqueda_, el objetivo es crear una lista de 4 fragmentos para que se asigne a cada tab el fragmento correspondiente a su funcion

**Comment by DreamaerD** [comment]
hecho

**Comment by crzyivo** [comment]
El buen switch
