### ISSUE TITLE
Problema Pestaña Mapa

### ISSUE THREAD

**Issue by ghost** [UNIZAR-30226-2017-04/barestv-android#5]
Al acceder al la pestaña mapa, carga el mapa y geolocalización correctamente. Si sales y vuelves a entrar la aplicación se cuelga. Además, creo que no guarda correctamente el estado de otras pestañas
![captura de pantalla 2017-05-10 a las 17 27 43](https://cloud.githubusercontent.com/assets/25644359/25907318/61ef4d46-35a7-11e7-826e-9f6a7891e3a6.png)
![captura de pantalla 2017-05-10 a las 17 27 53](https://cloud.githubusercontent.com/assets/25644359/25907319/62231e8c-35a7-11e7-8cd4-83211950cd9c.png)

**Comment by DreamaerD** [comment]
Lo de que no guarde el estado de otras pestañas es problema de esa pestañas, no tiene que ver con la pestaña de mapa

**Comment by DreamaerD** [comment]
http://stackoverflow.com/questions/27589590/error-inflating-class-fragment-duplicate-id-tag-null-or-parent-id-with-anoth

**Comment by ghost** [comment]
En el método onCreateView había que añadir una condición al inicio que sólo hiciese "view = inflater.inflate(R.layout.activity_maps, container, false);" si la variable era nula. No había que crearlo cada vez
